config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#home'
  get 'home/about', to: 'homes#about'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォロワー取得
  has_many :following_user, through: :follower, source: :followed #自分がフォローしてる
  has_many :follower_user, through: :followed, source: :follower #自分をフォローしている人

# ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーをフォロー解除する
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# 現在のユーザーがフォローしていたらtrueを返す
def following?(user)
  following.include?(user)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    end

    def after_sign_up_path_for(resource)
      user_path(resource)
    end

    def after_sign_in_path_for(resource)
      user_path(resource)
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      redirect_back(fallback_location: books_path)
      flash[:notice] = "successfully created comments!"
    else
      @book_comments = BookComment.where(book_id: @book.id)
      render "/books/show"
    end
  end

  def destroy
    @book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    if @book_comment.user == current_user
      @book_comment.destroy
      redirect_back(fallback_location: books_path)
    end
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
        redirect_to book_path(@book.id), notice: "You have creatad book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
     @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body, :user_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_back(fallback_location: books_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: books_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to user_path, notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h2>New book</h2>

<%= form_for(Book.new) do |f| %>

  <% if book.errors.any? %>
    <h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
    <%= book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>
  <div class="field row">
    <%= f.label "Opinion" %>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>
  <div class="actions row">
    <%= f.submit 'Create Book', class: "col-xs-12 btn btn-primary" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>

      <!-- いいねボタン -->
      <td>
        <% if book.favorited_by?(current_user) %>
          <%= link_to book_favorites_path(book), method: :delete do %>
            <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
            <%= book.favorites.count %>
          <% end %>
        <% else %>
          <%= link_to book_favorites_path(book), method: :post do %>
            <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
            <%= book.favorites.count %>
          <% end %>
        <% end %>
      </td>

      <td>
        コメント数:<%= book.book_comments.count %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>
    <%= form_for(@book) do |f| %>
    <%= render 'layouts/errors', obj: @book %>

      <div class="field row">
        <%= f.label :title %>
        <%= f.text_field :title, class: "col-xs-12" %>
      </div>
      <div class="field row">
        <%= f.label "Opinion" %>
        <%= f.text_area :body, class: "col-xs-12" %>
      </div>
      <div class="actions row">
        <%= f.submit 'Update Book', class: "col-xs-12 btn btn-primary" %>
      </div>
    <% end %>

    <%= link_to "Show", book_path(@book) %>|<%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class="row">
  <div class="col-xs-3">
    <%= render 'users/info', user: current_user %>
    <%= render 'books/form', book: Book.new %>
  </div>

  <div class="col-xs-9">
    <h2>Books</h2>
    <%= render 'books/index', books: @books %>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <%= render 'users/info', user: @book.user %>
    <%= render 'books/form', book: Book.new %>
  </div>

  <div class="col-xs-9">
    <h1>Book detail</h1>
    <table class="table">
      <tbody>
        <tr>
          <td>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format: "jpeg", fallback: "no_image.jpg" %><br>
            <%= link_to @book.user.name, user_path(@book.user) %>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>

          <!-- いいねボタン -->
          <td>
            <% if @book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
                <%= @book.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book), method: :post do %>
                <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
                <%= @book.favorites.count %>
              <% end %>
            <% end %>
          </td>
          <td>
            コメント数:<%= @book.book_comments.count %>
          </td>

          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" =>  "本当に消しますか?", class: "btn btn-danger" %></td>
          <% end %>
        </tr>
      </tbody>
    </table>


    <!-- コメント一覧 -->
    <table>
      <tbody>
        <% @book.book_comments.each do |book_comment| %>
          <tr>
              <td><%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, format: "jpeg", fallback: "no_image.jp" %><br>
                  <%= book_comment.user.name %>
              </td>
              <td><%= book_comment.comment %></td>

              <% if book_comment.user == current_user %>
                <td><%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger" %>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- コメントフォーム -->
    <%= form_for [@book, @book_comment] do |f| %>
      <%= f.text_area :comment, size: '90x5' %>
      <%= f.submit "送信" %>
    <% end %>
  </div>
</div>

app/views/homes/about.html.erb
<h1>
  Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong>!</span>
</h1>

app/views/homes/home.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>
      welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong> !!</span>
    </h1>

    <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,</p>

    <p>you can share and exchange your opinions , inpressions , and emotions</p>

    <p>about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explantion">
    <h3><%= obj.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to  " Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to  " Users", users_path, class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to  " Books", books_path, class: "glyphicon glyphicon-book" %></li>
              <li><%= link_to  " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %></li>
            <% else %>
              <li><%= link_to  " Home", root_path, class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to  " About", home_about_path, class: "glyphicon glyphicon-link" %></li>
              <li><%= link_to  " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
              <li><%= link_to  " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <div class="body">
      <div class="container">
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-default col-xs-12" do %>
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
    <% end %>
</div>

<!-- 
<a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_23676" href="/users/23676/edit"></a> -->

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>
  <%= render 'layouts/errors', obj: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%=f.label "Image" %>
    <%= f.attachment_field :profile_image %>
  </div>
  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction %>
  </div>
  <div class="actions">
    <%= f.submit 'Update User' %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">
    <%= render 'users/info', user: current_user %>

    <%= render 'books/form', book: Book.new %>
  </div>

  <div class="col-xs-9">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <%= render 'users/info', user: @user %>
    <%= render 'books/form', book: Book.new %>
  </div>

  <div class="col-xs-9">
    <h2>Books</h2>
    <%= render 'books/index', books: @books %>
  </div>
</div>